name: Deploy to Production

on: # yamllint disable-line rule:truthy
  release:
    types: [released, published]
  workflow_dispatch:

jobs:
  deploy:
    name: Run Deployment
    uses: eunseochoi/test-repo/.github/workflows/test-deploy.yaml@main
    # gh actions mark all events relating to release as 'release' (including prerelease), so we need an additional check to not deploy pre-releases
    if: ((github.event_name == 'release' && github.event.action == 'released') || github.event_name == 'workflow_dispatch')
    secrets: inherit
