name: Run on Latest Tag

on:
  schedule:
    - cron: "0 0 * * *"  # Adjust this cron schedule as needed, currently runs daily at midnight UTC

jobs:
  run-latest-tag:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-tags: true  # Ensure all tags are fetched

    - name: List all tags (for debugging)
      run: git tag

    - name: Get the latest tag
      id: get_latest_tag
      run: |
        latest_tag=$(git describe --tags `git rev-list --tags --max-count=1` || echo "none")
        if [ "$latest_tag" = "none" ]; then
          echo "No tags found. Exiting..."
          exit 0
        fi
        echo "latest_tag=${latest_tag}" >> $GITHUB_ENV

    - name: Check out the latest tag
      if: ${{ env.latest_tag != 'none' }}
      run: git checkout ${{ env.latest_tag }}

  deploy:
    needs: run-latest-tag
    if: ${{ github.event.env.latest_tag != 'none' && github.event_name == 'schedule' }}
    uses: <owner>/<repo>/.github/workflows/deploy.yaml@${{ env.latest_tag }}
    secrets: inherit