name: Deploy to Production

on: # yamllint disable-line rule:truthy
  release:
    types: [published]
  workflow_dispatch:
  repository_dispatch:
    types: [deploy-to-prod]
    inputs:
      skip_check:
        description: "Set to true to skip the task protection check. WARNING! If there is a task with active protection, then this will trigger an infinite scale! Check with #eng-data before toggling this."
        required: false
        default: false
        type: boolean

jobs:
  promote-release:
    runs-on: ubuntu-latest

    steps:
    - name: Check Local Time
      id: no-op
      run: |
          echo "running test check protection"
