name: Deploy to Production

on: # yamllint disable-line rule:truthy
  release:
    types: [published, released]
  workflow_dispatch:
    inputs:
      skip_check:
        description: "Set to true to skip the task protection check. WARNING! If there is a task with active protection, then this will trigger an infinite scale! Check with #eng-data before toggling this."
        required: false
        default: false
        type: boolean

jobs:
  test-job-1:
    runs-on: ubuntu-latest
    if: github.event_name == 'release'
    steps:
    - name: Check Local Time
      id: no-op
      run: |
          echo "running test job 1"
  
  test-job-2:
    runs-on: ubuntu-latest
    if: github.event_name == 'release' && github.action == 'released'
    steps:
    - name: Check Local Time
      id: no-op
      run: |
          echo "running test job 2"
