name: Deploy to Production

on: # yamllint disable-line rule:truthy
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      skip_check:
        description: "Set to true to skip the task protection check. WARNING! If there is a task with active protection, then this will trigger an infinite scale! Check with #eng-data before toggling this."
        required: false
        default: false
        type: boolean

jobs:
  check:
    if: "!github.event.release.prerelease"
    name: Check Task Protection
    run: |
        echo "running test check protection"
