name: Deploy to Production

on: # yamllint disable-line rule:truthy
  schedule:
    - cron: "10 4 * * *" # 00:10 EDT
    - cron: "10 5 * * *" # 00:10 EST
  workflow_dispatch:
    inputs:
      skip_check:
        description: "Set to true to skip the task protection check. WARNING! If there is a task with active protection, then this will trigger an infinite scale! Check with #eng-data before toggling this."
        required: false
        default: false
        type: boolean

jobs:
  test-job-1:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Get the latest release
      id: get_latest_release
      uses: actions/github-script@v6
      with:
        script: |
          const latestRelease = await github.rest.repos.getLatestRelease({
            owner: context.repo.owner,
            repo: context.repo.repo
          });
          core.setOutput('tag_name', latestRelease.data.tag_name);
    - name: Fake deployment
      # echo the current action
      run: |
          echo "running test job 2"
          echo "github.branch: ${{ github.ref }}"

