name: Promote Pre-Release

on: # yamllint disable-line rule:truthy
  schedule:
    - cron: "10 4 * * *" # 00:10 EDT
    - cron: "10 5 * * *" # 00:10 EST

  workflow_dispatch:

jobs:
  call-scheduled-release:
    name: Promote Pre-Release at Midnight
    uses: eunseochoi/test-repo/.github/workflows/scheduled-full-release.yaml@main
    with:
      repository: "test-actions"
      start-time: "00:00"
      end-time: "23:30"
